### ISSUE TITLE
我在执行run.sh遇到问题

### ISSUE THREAD

**Issue by wdxwj** [PaddlePaddle/PALM#89]
creating readers...
loading mrqa training data...
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py:721: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  'paddle.fluid.layers.py_reader() may be deprecated in the near future. '
WARNING:root:paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
Traceback (most recent call last):
  File "mtl_run.py", line 397, in <module>
    train(multitask_config)
  File "mtl_run.py", line 134, in train
    joint_generator, train_pyreader, model_inputs = create_reader("train_reader", train_input_shape, True, task_map_id, gens)
  File "reader/joint_reader.py", line 84, in create_reader
    pyreader, model_inputs = placeholder.build(capacity=16, reader_name=reader_name)
  File "/home/aistudio/multi_task_learning/PALM/utils/placeholder.py", line 64, in build
    use_double_buffer = use_double_buffer)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 729, in py_reader
    use_double_buffer=use_double_buffer)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 453, in _py_reader
    'ranks': ranks
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3009, in append_op
    kwargs.get("stop_gradient", False))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE (at /paddle/paddle/fluid/pybind/imperative.cc:221)

**Comment by zhengvh** [comment]
我也遇见的相同的问题，环境是：AI Studio上的PaddlePaddle 2.0
